    vendor/samsung/jflteusc/proprietary/bin/efsks:system/bin/efsks \
    vendor/samsung/jflteusc/proprietary/bin/ks:system/bin/ks \
    vendor/samsung/jflteusc/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/samsung/jflteusc/proprietary/bin/qcks:system/bin/qcks \
    vendor/samsung/jflteusc/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/jflteusc/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/jflteusc/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/jflteusc/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    vendor/samsung/jflteusc/proprietary/lib/libcnefeatureconfig.so:system/lib/libcnefeatureconfig.so \
    vendor/samsung/jflteusc/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/jflteusc/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/jflteusc/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/jflteusc/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/jflteusc/proprietary/lib/librmnetctl.so:system/lib/librmnetctl.so \
    vendor/samsung/jflteusc/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/jflteusc/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/jflteusc/proprietary/lib/libxml.so:system/lib/libxml.so \
    vendor/samsung/jflteusc/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/samsung/jflteusc/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/jflteusc/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/jflteusc/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/samsung/jflteusc/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/jflteusc/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/samsung/jflteusc/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/jflteusc/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/jflteusc/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/jflteusc/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/jflteusc/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/jflteusc/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/jflteusc/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/samsung/jflteusc/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/samsung/jflteusc/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so
