# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/hltedcm-oneseg/setup-makefiles.shon
## FeliCa
PRODUCT_COPY_FILES += \
	vendor/samsung/hltedcm-oneseg/proprietary/bin/broadcastProcessObserver:system/bin/broadcastProcessObserver \
	vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bml.db:system/etc/one-seg/bml.db \
	vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_0.wav:system/etc/one-seg/bmlrom_0.wav \
	vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_1.wav:system/etc/one-seg/bmlrom_1.wav \
	vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_2.wav:system/etc/one-seg/bmlrom_2.wav \
	vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_3.wav:system/etc/one-seg/bmlrom_3.wav \
	vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_4.wav:system/etc/one-seg/bmlrom_4.wav \
	vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_5.wav:system/etc/one-seg/bmlrom_5.wav \
	vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_6.wav:system/etc/one-seg/bmlrom_6.wav \
	vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_7.wav:system/etc/one-seg/bmlrom_7.wav \
	vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_8.wav:system/etc/one-seg/bmlrom_8.wav \
	vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_9.wav:system/etc/one-seg/bmlrom_9.wav \
	vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_10.wav:system/etc/one-seg/bmlrom_10.wav \
	vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_11.wav:system/etc/one-seg/bmlrom_11.wav \
	vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_12.wav:system/etc/one-seg/bmlrom_12.wav \
	vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_13.wav:system/etc/one-seg/bmlrom_13.wav \
	vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_14.wav:system/etc/one-seg/bmlrom_14.wav \
	vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_15.wav:system/etc/one-seg/bmlrom_15.wav \
	vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/debug.ini:system/etc/one-seg/debug.ini \
	vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/njccp932.ctb:system/etc/one-seg/njccp932.ctb \
	vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/tvfiles_database.db:system/etc/one-seg/tvfiles_database.db \
	vendor/samsung/hltedcm-oneseg/proprietary/lib/libBroadcastProcObs.so:system/lib/libBroadcastProcObs.so \
	vendor/samsung/hltedcm-oneseg/proprietary/lib/libOneSegfactorytest_jni_fb.so:system/lib/libOneSegfactorytest_jni_fb.so \
	vendor/samsung/hltedcm-oneseg/proprietary/lib/libPGL.so:system/lib/libPGL.so \
	vendor/samsung/hltedcm-oneseg/proprietary/lib/libnextbitd.so:system/lib/libnextbitd.so \
	vendor/samsung/hltedcm-oneseg/proprietary/lib/libnextbitservice_jni.so:system/lib/libnextbitservice_jni.so \
	vendor/samsung/hltedcm-oneseg/proprietary/lib/libonesegbmlpeer.so:system/lib/libonesegbmlpeer.so \
	vendor/samsung/hltedcm-oneseg/proprietary/lib/libonesegdmxdriver.so:system/lib/libonesegdmxdriver.so \
	vendor/samsung/hltedcm-oneseg/proprietary/lib/libonesegdsmcc.so:system/lib/libonesegdsmcc.so \
	vendor/samsung/hltedcm-oneseg/proprietary/lib/libonesegsp.so:system/lib/libonesegsp.so \
	vendor/samsung/hltedcm-oneseg/proprietary/lib/libonesegutils.so:system/lib/libonesegutils.so 

