# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/hltedcm-oneseg/setup-makefiles.shon
## FeliCa
#PRODUCT_COPY_FILES += \
#	vendor/vendor/samsung/hltedcm-oneseg/proprietary/app/ISDBT_FactoryTest.apk:system/app/ISDBT_FactoryTest.apk \
#	vendor/vendor/samsung/hltedcm-oneseg/proprietary/app/MobileTV_JPN_PHONE_K.apk:system/app/MobileTV_JPN_PHONE_K.apk 

PRODUCT_COPY_FILES += \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/bin/broadcastProcessObserver:system/bin/broadcastProcessObserver \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bml.db:system/etc/one-seg/bml.db \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_0.wav:system/etc/one-seg/bmlrom_0.wav \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_1.wav:system/etc/one-seg/bmlrom_1.wav \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_10.wav:system/etc/one-seg/bmlrom_10.wav \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_11.wav:system/etc/one-seg/bmlrom_11.wav \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_12.wav:system/etc/one-seg/bmlrom_12.wav \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_13.wav:system/etc/one-seg/bmlrom_13.wav \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_14.wav:system/etc/one-seg/bmlrom_14.wav \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_15.wav:system/etc/one-seg/bmlrom_15.wav \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_2.wav:system/etc/one-seg/bmlrom_2.wav \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_3.wav:system/etc/one-seg/bmlrom_3.wav \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_4.wav:system/etc/one-seg/bmlrom_4.wav \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_5.wav:system/etc/one-seg/bmlrom_5.wav \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_6.wav:system/etc/one-seg/bmlrom_6.wav \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_7.wav:system/etc/one-seg/bmlrom_7.wav \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_8.wav:system/etc/one-seg/bmlrom_8.wav \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/bmlrom_9.wav:system/etc/one-seg/bmlrom_9.wav \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/debug.ini:system/etc/one-seg/debug.ini \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/njccp932.ctb:system/etc/one-seg/njccp932.ctb \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/etc/one-seg/tvfiles_database.db:system/etc/one-seg/tvfiles_database.db \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/etc/permissions/mmb.xml:system/etc/permissions/mmb.xml \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/framework/MmbFcBrowMw-res/MmbFcBrowMw-res.apk:system/framework/MmbFcBrowMw-res/MmbFcBrowMw-res.apk \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/framework/MmbFcBrowMw.jar:system/framework/MmbFcBrowMw.jar \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/framework/MmbFcContMw.jar:system/framework/MmbFcContMw.jar \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/framework/MmbFcIndivdMw.jar:system/framework/MmbFcIndivdMw.jar \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/framework/MmbFcMfestMw.jar:system/framework/MmbFcMfestMw.jar \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/framework/MmbFcMp4Mw.jar:system/framework/MmbFcMp4Mw.jar \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/framework/MmbFcPgInfoMw.jar:system/framework/MmbFcPgInfoMw.jar \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/framework/MmbMoInfoMw.jar:system/framework/MmbMoInfoMw.jar \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/framework/MmbPoServiceSp.jar:system/framework/MmbPoServiceSp.jar \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/framework/MmbScSecClkMw.jar:system/framework/MmbScSecClkMw.jar \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/framework/MmbSeMngMw.jar:system/framework/MmbSeMngMw.jar \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/framework/MmbServiceLibrary.jar:system/framework/MmbServiceLibrary.jar \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/framework/MmbSetting/MmbSetting.apk:system/framework/MmbSetting/MmbSetting.apk \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/framework/MmbStBmlMw.jar:system/framework/MmbStBmlMw.jar \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/framework/MmbStCtlMw.jar:system/framework/MmbStCtlMw.jar \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/framework/MmbStRecCmMw.jar:system/framework/MmbStRecCmMw.jar \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/framework/MmbStRecMw.jar:system/framework/MmbStRecMw.jar \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/framework/minimode.jar:system/framework/minimode.jar \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/framework/sechardware.jar:system/framework/sechardware.jar \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/lib/libBroadcastProcObs.so:system/lib/libBroadcastProcObs.so \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/lib/libOneSegfactorytest_jni_fb.so:system/lib/libOneSegfactorytest_jni_fb.so \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/lib/libPGL.so:system/lib/libPGL.so \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/lib/libnextbitd.so:system/lib/libnextbitd.so \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/lib/libnextbitservice_jni.so:system/lib/libnextbitservice_jni.so \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/lib/libonesegbmlpeer.so:system/lib/libonesegbmlpeer.so \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/lib/libonesegdmxdriver.so:system/lib/libonesegdmxdriver.so \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/lib/libonesegdsmcc.so:system/lib/libonesegdsmcc.so \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/lib/libonesegsp.so:system/lib/libonesegsp.so \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/lib/libonesegutils.so:system/lib/libonesegutils.so

PRODUCT_COPY_FILES += \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/framework/twframework-res.apk:system/framework/twframework-res.apk \
	vendor/vendor/samsung/hltedcm-oneseg/proprietary/framework/twframework.jar:system/framework/twframework.jar
