# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/kltedcm/setup-makefiles.sh

## snfc
PRODUCT_COPY_FILES += \
	vendor/samsung/kltedcm/proprietary/snfc/etc/snfc/auto_polling.cfg:system/etc/snfc/auto_polling.cfg \
	vendor/samsung/kltedcm/proprietary/snfc/etc/snfc/rf.cfg:system/etc/snfc/rf.cfg \
	vendor/samsung/kltedcm/proprietary/snfc/lib/libnfc_sony.so:system/lib/libnfc_sony.so \
	vendor/samsung/kltedcm/proprietary/snfc/lib/libnfc_sony_jni.so:system/lib/libnfc_sony_jni.so \
	vendor/samsung/kltedcm/proprietary/snfc/lib/libnfc_sony_ndef.so:system/lib/libnfc_sony_ndef.so

# spmode mail
#PRODUCT_COPY_FILES += \
#	vendor/samsung/kltedcm/proprietary/app/SPModePushNotifier.apk:system/app/SPModePushNotifier/SPModePushNotifier.apk \
#	vendor/samsung/kltedcm/proprietary/fonts/truetypeEmoji.ttf:system/fonts/truetypeEmoji.ttf \
#	vendor/samsung/kltedcm/proprietary/lib/libemoji_docomo.so:system/lib/libemoji_docomo.so
