# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/js01lte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/js01lte/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    vendor/samsung/js01lte/proprietary/lib/hw/flp.default.so:system/lib/hw/flp.default.so \
    vendor/samsung/js01lte/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/samsung/js01lte/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/samsung/js01lte/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/samsung/js01lte/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/samsung/js01lte/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    vendor/samsung/js01lte/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/js01lte/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/samsung/js01lte/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/js01lte/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/js01lte/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/js01lte/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/js01lte/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/js01lte/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/js01lte/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/js01lte/proprietary/vendor/lib/libqmi_csvt_srvc.so:system/vendor/lib/libqmi_csvt_srvc.so \
    vendor/samsung/js01lte/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/samsung/js01lte/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/samsung/js01lte/proprietary/bin/efsks:system/bin/efsks \
    vendor/samsung/js01lte/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/samsung/js01lte/proprietary/bin/ks:system/bin/ks \
    vendor/samsung/js01lte/proprietary/bin/qcks:system/bin/qcks \
    vendor/samsung/js01lte/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/js01lte/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/samsung/js01lte/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/js01lte/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/js01lte/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/js01lte/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/js01lte/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/js01lte/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/js01lte/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/js01lte/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/js01lte/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/js01lte/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so
