# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/js01lte-felica/setup-makefiles.shon
## FeliCa
PRODUCT_COPY_FILES += \
	vendor/samsung/js01lte-felica/proprietary/felica/app/MobileFeliCaClient.apk:system/app/MobileFeliCaClient/MobileFeliCaClient.apk \
	vendor/samsung/js01lte-felica/proprietary/felica/app/MobileFeliCaMenuApp.apk:system/app/MobileFeliCaMenuApp/MobileFeliCaMenuApp.apk \
	vendor/samsung/js01lte-felica/proprietary/felica/app/MobileFeliCaSettingApp.apk:system/app/MobileFeliCaSettingApp/MobileFeliCaSettingApp.apk \
	vendor/samsung/js01lte-felica/proprietary/felica/app/MobileFeliCaWebPluginBoot.apk:system/app/MobileFeliCaWebPluginBoot/MobileFeliCaWebPluginBoot.apk \
	vendor/samsung/js01lte-felica/proprietary/felica/bin/mfdp:system/bin/mfdp \
	vendor/samsung/js01lte-felica/proprietary/felica/bin/mfsc:system/bin/mfsc \
	vendor/samsung/js01lte-felica/proprietary/felica/etc/felica/common.cfg:system/etc/felica/common.cfg \
	vendor/samsung/js01lte-felica/proprietary/felica/etc/felica/mfc_falp.cfg:system/etc/felica/mfc_falp.cfg \
	vendor/samsung/js01lte-felica/proprietary/felica/etc/felica/mfc_push.cfg:system/etc/felica/mfc_push.cfg \
	vendor/samsung/js01lte-felica/proprietary/felica/etc/felica/mfm.cfg:system/etc/felica/mfm.cfg \
	vendor/samsung/js01lte-felica/proprietary/felica/etc/felica/mfs.cfg:system/etc/felica/mfs.cfg \
	vendor/samsung/js01lte-felica/proprietary/felica/etc/osaifu/osaifu.cfg:system/etc/osaifu/osaifu.cfg \
	vendor/samsung/js01lte-felica/proprietary/felica/lib/libcordon.so:system/lib/libcordon.so \

## snfc
PRODUCT_COPY_FILES += \
	vendor/samsung/js01lte-felica/proprietary/snfc/etc/snfc/auto_polling.cfg:system/etc/snfc/auto_polling.cfg \
	vendor/samsung/js01lte-felica/proprietary/snfc/etc/snfc/rf.cfg:system/etc/snfc/rf.cfg \
	vendor/samsung/js01lte-felica/proprietary/snfc/lib/libnfc_sony.so:system/lib/libnfc_sony.so \
	vendor/samsung/js01lte-felica/proprietary/snfc/lib/libnfc_sony_jni.so:system/lib/libnfc_sony_jni.so \
	vendor/samsung/js01lte-felica/proprietary/snfc/lib/libnfc_sony_ndef.so:system/lib/libnfc_sony_ndef.so

# spmode mail
#PRODUCT_COPY_FILES += \
#	vendor/samsung/js01lte-felica/proprietary/app/SPModePushNotifier.apk:system/app/SPModePushNotifier/SPModePushNotifier.apk \
#	vendor/samsung/js01lte-felica/proprietary/fonts/truetypeEmoji.ttf:system/fonts/truetypeEmoji.ttf \
#	vendor/samsung/js01lte-felica/proprietary/lib/libemoji_docomo.so:system/lib/libemoji_docomo.so
